server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: client-service

feign:
  circuitbreaker:
    enabled: true
---
spring:
 sleuth:
   sampler:
     probability: 2.0

logging:
  file:
    name: C:\Users\redmi\Log\application.log

