
server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: book-service
---
spring:
  data:
   mongodb:
     uri: mongodb://localhost:27017/mongo

---
spring:
  sleuth:
    sampler:
      probability: 2.0
