spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_ADDR:http://localhost:9092}
    bus:
      enabled: true
      id: config-server
server:
  port: 8886
---
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Denis-de/ms-config-properties.git
          search-paths:
             -"/{application}/{profile}"
          default-label: master
          username: Denis-de
          password: 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
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
         search-locations: /redmi/IdeaProjects/ms-config-properties/{application}/{profile}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}