spring:
  profiles:
    active: native
  application:
    name: config-server
server:
  port: 8888
---
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Denis-de/ms-config-properties
          search-paths: "/ms-config-properties/{application}/{profile}"
          default-label: main

      #spring:
 # config:
  #  activate:
   #   on-profile: native
 # cloud:
  #  config:
   #   server:
    #    native:
     #    search-locations: /redmi/IdeaProjects/ms-config-properties/config-client/{application}/{profile}
